# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Test API GATEWAY with Maven
      run:  cd api-gateway && mvn -B test --file pom.xml && cd ../
    - name: Test BATTLESHIP QUEUE with Maven
      run: cd battleship-queue && mvn -B test --file pom.xml && cd ../
    - name: Test BATTLESHIP GAME with Maven
      run: cd battleship-game && mvn -B test --file pom.xml && cd ../
    - name: Test USER PROFILE with Maven
      run: cd user-profile && mvn -B test --file pom.xml && cd ../
    - name: Upload coverage to Codecov package 1
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
